steps:
  #install angular
- name: 'gcr.io/cloud-builders/npm'
  id: 'Install Angular'
  args: 
    - 'install'
    - '-g'
    - '@angular/cli'

# Install Dependencies
- name: 'gcr.io/cloud-builders/npm'
  id: 'Install Project Dependencies'
  args: 
    - 'install'
  
# This step run the unit tests
- name: 'gcr.io/cloud-builders/npm'
  id: 'Test'
  args: 
    - 'run'
    - 'ng'
    - 'test'
    - '-browsers'
    - 'ChromeHeadless'
  
  # Build productive files
- name: 'gcr.io/cloud-builders/npm'
  id: 'Complie'
  args: 
    - 'run' 
    - 'ng'
    - 'build'
    - '--prod'
    - '--aot'

  # This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/website-cloudbuild:$SHORT_SHA'
    - '.'

  # This step pushes the image to container registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build
- name: 'gcr.io/clough-builders/docker'
  id: Push
  args: 
    - 'push'
    - 'gcr.io/$PROJECT_ID/website-cloudbuild:$SHORT_SHA'
