# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: node
  entrypoint: npm
  id: 'Installing dependencies'
  args: ['install']

- name: node
  entrypoint: npm
  id: 'Compiling/Building project'
  env:
    - 'MAINTENANCE_MODE=${_MAINTENANCE_MODE}'
  args: ['run','build']

- name: gcr.io/my-website-a3970/firebase
  id: 'Deploying to Firebase'
  args: ['deploy', '--project=my-website-a3970', '--only=hosting']