# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
- name: gcr.io/cloud-builders/npm
  id: 'Instal dependencies'
  args: ['install']

- name: gcr.io/cloud-builders/npm
  id: 'Build the project'
  env:
    - 'MAINTENANCE_MODE=${_MAINTENANCE_MODE}'
  args: ['run','build']

- name: gcr.io/my-website-a3970/firebase@sha256:48b2e9463a3d3977d1b4fe9ad6c86ec3a7dddeb1bbdf0b510ad6ea6f4d591ec0
  id: 'Deploy to Firebase'
  args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']