apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: websiteweb
  labels:
    app: website
spec:
  selector:
    matchLabels:
      app: website
      tier: web
  template:
    metadata:
      labels:
        app: website
        tier: web
        sha: ${SHORT_SHA}
    spec:
      containers:
      - name: website-app
        image: gcr.io/website-227817/website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: websiteweb-backend
  labels:
    app: website
spec:
  type: NodePort
  selector:
    app: website
    tier: web
  ports:
  - port: 8080
    targetPort: 8080
