apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: website
    spec:
      containers:
      - name: website
        image: clough/website:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    run: website
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    run: website
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website
spec:
  rules:
  - http:
      paths:
        - path: /*
          backend:
            serviceName: website
            servicePort: 80