apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    run: website
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: website
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: website
    spec:
      containers:
      - name: website
        image: clough/website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443      