apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: website
    spec:
      containers:
      - name: website
        image: gcr.io/website-227817/website:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    app: website
spec:
  type: NodePort
  selector:
    app: website
    tier: web
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: website-ip
  labels:
    app: website
spec:
  backend:
    serviceName: website-service
    servicePort: 8080
