steps:
  # This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/website:latest'
    - '.'

  # This step pushes the image to container registry
  # The PROJECT_ID and SHORT_SHA variables are automatically
  # replaced by Cloud Build
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/website:latest'

# generate new deployment yaml based on $SHORT_SHA
- name: 'gcr.io/$PROJECT_ID/envsubst'
  id: 'Substituting Environment Values'
  args:
    - 'deployment.yaml'
    - 'deployment.yaml'
  env:
    - 'SHORT_SHA=$SHORT_SHA'

# Deploy application on kubernetes
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Deploy on Kubernetes'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CONTAINER_CLUSTER}'
    - 'SHORT_SHA=$SHORT_SHA'
  args:
    - 'apply'
    - '-f'
    - 'deployment.yaml'
