#!/bin/bash
# Firebase Web App Configuration Setup Script
# This script will help you get the correct Firebase configuration

echo "🔥 Firebase Web App Configuration Setup"
echo "========================================"
echo ""
echo "Your current Firebase project: my-website-a3970"
echo "Current server account credentials are working ✓"
echo ""
echo "⚠️  ISSUE: Missing Firebase Web App Configuration"
echo "The 'auth/internal-error' occurs because your .env file has dummy values."
echo ""
echo "📋 Follow these steps to get your real Firebase web config:"
echo ""
echo "1. Open Firebase Console:"
echo "   https://console.firebase.google.com/project/my-website-a3970"
echo ""
echo "2. Go to Project Settings:"
echo "   - Click the gear icon (⚙️) in the left sidebar"
echo "   - Select 'Project settings'"
echo ""
echo "3. Add a Web App (if not already done):"
echo "   - Scroll down to 'Your apps' section"
echo "   - If you see a web app (</> icon), skip to step 4"
echo "   - If no web app exists:"
echo "     • Click 'Add app' button"
echo "     • Select 'Web' (</> icon)"
echo "     • App nickname: 'My Website'"
echo "     • Check 'Also set up Firebase Hosting'"
echo "     • Click 'Register app'"
echo ""
echo "4. Get the Configuration:"
echo "   - You'll see a code snippet like this:"
echo ""
echo "   const firebaseConfig = {"
echo "     apiKey: \"AIzaSyC...\","
echo "     authDomain: \"my-website-a3970.firebaseapp.com\","
echo "     projectId: \"my-website-a3970\","
echo "     storageBucket: \"my-website-a3970.appspot.com\","
echo "     messagingSenderId: \"123456789\","
echo "     appId: \"1:123456789:web:abcdef123456\""
echo "   };"
echo ""
echo "5. Update your .env file with these values:"
echo "   FIREBASE_API_KEY=AIzaSyC...                    # Copy from apiKey"
echo "   FIREBASE_MESSAGING_SENDER_ID=123456789         # Copy from messagingSenderId"
echo "   FIREBASE_APP_ID=1:123456789:web:abcdef123456   # Copy from appId"
echo ""
echo "6. Enable Authentication:"
echo "   - In Firebase Console, go to 'Authentication'"
echo "   - Click 'Sign-in method' tab"
echo "   - Click on 'Google' provider"
echo "   - Toggle 'Enable'"
echo "   - Add your email address"
echo "   - Save"
echo ""
echo "7. Add Authorized Domain:"
echo "   - Still in Authentication → Sign-in method"
echo "   - Scroll to 'Authorized domains'"
echo "   - Add: localhost"
echo "   - Save"
echo ""
echo "8. Test Your Setup:"
echo "   - Restart your Go server"
echo "   - Visit: http://localhost:8082/admin/login"
echo "   - Click 'Sign in with Google'"
echo "   - It should work! 🎉"
echo ""
echo "💡 Need help? Check the detailed guide in:"
echo "   scripts/get-firebase-config.md"
echo ""
echo "🔧 If you get the config values, run this to update:"
echo "   nano .env"
echo "   # Then restart: go run main.go"
echo ""